config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :tools, :techniques, only: [:index, :show]

end

app/models/technique.rb
class Technique < ActiveRecord::Base
  validates :title, :subtitle, :description, :link, presence: true
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :title, :subtitle, :description, :link, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
    @techniques = Technique.all
  end

  def show
    @technique = Technique.find(params[:id])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.all
  end

  def show
    @tool = Tool.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.erb
<%= link_to "home", "/" %>
<%= link_to "tools", tools_path %>
<%= link_to 'techniques', techniques_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "#{@page_title} | Toolsentechnieken" || "Toolsentechnieken" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "navigation" %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<% @page_title = 'Home' %>
<h1>home</h1>

app/views/techniques/index.html.erb
<% @page_title = 'Techniques' %>
<h1>Techniques :)</h1>

<% @techniques.each do |technique| %>
  <%= link_to technique.title, technique_path(technique.id) %>
<% end %>

app/views/techniques/show.html.erb
<h1><%= @technique.title %></h1>
<small><%= @technique.subtitle %></small>

<p>
  <%= @technique.description %><br>

  Voor meer informatie, ga naar: <%= link_to @technique.link, @technique.link %>
</p>

<%= link_to 'Back', techniques_path %>

app/views/tools/index.html.erb
<% @page_title = 'Tools' %>
<h1>tools gedeeltuhhh</h1>

<% @tools.each do |tool| %>
  <%= link_to tool.title, tool_path(tool.id) %>
<% end %>

app/views/tools/show.html.erb
<h1><%= @tool.title %></h1>
<small><%= @tool.subtitle %></small>

<p>
  <%= @tool.description %><br>

  Voor meer informatie, ga naar: <%= link_to @tool.link, @tool.link %>
</p>

<%= link_to 'Back', tools_path %>